# Learning to program with python

 ressources
 - http://www.scipy.org/topical-software.html

 ipython notebooks, and latex magic

 python is a popular XXth generation programming language
 Pro: 
 - it's a "real" language 
 - that gives developers slack: "multiparadigm" OO, procedural, functional programming styles
 - efficient language: get stuff done with few lines 
 - readable 
 - popular in the scientific community
 - modules offer advanced algebraic, graphics, ... capabilities 
 - dynamically typed 
 - automatic memory management
 - open source, free 


 Contra: 
 - speed
 - many independent developers, thus heterogeneous modules and conventions
 - dynamically typed 
 - little used in mobile computing 

 components
 - kernel 
 - integrated development environment (IDE)



### python is a pocket calculator


In [50]:
5*4  # int 

20

In [14]:
5*3. # float 

15.0

In [56]:
2.**64

1.8446744073709552e+19

In [52]:
5 / 3  # = 1 if you use python 2.7, = 1.666666... if you use python 3.5

1.6666666666666667

### python is a dynamically typed programming language
variables are used to store information

In [67]:
a12 = 3 
b = 5. 
text='hello'
type(text)
text = 3.14
t = [0,1,2,3,4]
type(t)

list

Tuples (1,2,3,4,5) are **immutable**,
Lists t=[1,2,3,4] can be altered: t.append(5)

In [70]:

t.append(9)
t

[0, 1, 2, 3, 4, 9, 9]

now check out the "variable explorer" 

computers use loops to work for us: 

In [17]:
for i in (0, 1, 2, 3, 4):
    print(i)

0
1
2
3
4


 plenty to digest here: 

 The `for` construct loops over elements of a sequence.
 Variable `i` is iteratively set to all elements of the sequence

 `(...)` define a "tuple", an immutable object 

 A colon `:` is needed. Why? Guido van Rossum, BDFL, argues 
 - that it helps readability, making the code sound "more English"
 - that it makes life easier for context-aware editors. 

 In python, **indentation matters** -- four spaces for each level of nestedness

In [72]:
for i in (1, 2, 3): 
    print(i)
    print(i**2) # exponentiation

1
1
2
4
3
9


is different from 

In [21]:
for i in (1, 2, 3): 
    print(i)
print(i**2) # exponentiation

1
2
3
9


for bigger loops, define range as follows: 

In [23]:
for i in range(5): # note: we get five elements, but starting at zero!
    print(i, i**2, i**3)  

0 0 0
1 1 1
2 4 8
3 9 27
4 16 64


In [25]:
# use steps: 
for i in range(1, 7, 2): #note: arguments of range are inclusive, exclusive, 
                         #      and step size
    print(i, i**2, i**3)  

1 1 1
3 9 27
5 25 125


One more word on **print**:

In [24]:
print(5)
print('hello')
print([1,2,3,4,5])

5
hello
[1, 2, 3, 4, 5]


In [29]:
print('hello', 5, [1,2,3])

hello 5 [1, 2, 3]


In [31]:
print('this is a {} with formatting'.format(5)) # {} is a placeholder

this is a 5 with formatting


In [30]:
print('this is a {:03d} with formatting'.format(5))

this is a 005 with formatting


### Arrays
Let's use an array to store a tensor of homogeneous values     

In [82]:
import numpy as np # We are importing a module. Such lines should really always 
                   # be at the very top of a script 

# todo: namespaces
a = np.ndarray([5, 3]) # allocate space for an array. 
b = np.array([ [1,2,3], [4,5,6] ]) # create an array filled with values
b

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
for i in range(5): #note: arguments of range are inclusive, exclusive, and step size
    a[i, :] = (i, i**2, i**3)  
    
# a[2]
# a[2,2]
a

array([[  0.,   0.,   0.],
       [  1.,   1.,   1.],
       [  2.,   4.,   8.],
       [  3.,   9.,  27.],
       [  4.,  16.,  64.]])

In [16]:
b.shape # gives us number of rows and columns

(2, 3)

In [81]:
b[0, 1]

2

In [17]:
b[:, 2] # note: colon means "all elements along this axis". 2 is the last column (zero based index!)

array([3, 6])

In [20]:
b[-1, 1] # using negative indices allows you to index from behind. -1 is last row, second value

5

### Conditions
What if we want to do different things depending on a condition?

In [85]:
a = -123
if a < 0:
    print("found negative number!") #note: strings can be enclosed in single or double quotes
else:
    print("a is non-negative")

found negative number!


In [86]:
a = 0
if a < 0:
    print("found negative number!")
elif a == 0:
    print("found zero")
else:
    print("a is positive")

found zero


Comparison operators are:

* relations: `<`, `>`, `<=`, `>=`
* equality / inequality: `==`, `!=`
* if we want to see whether a value is contained in a sequence/tuple/range: `in`

Conditions can be combined and negated:

* `not` COND
* COND1 `and` COND2
* COND1 `or` COND2

Parentheses can be used to group conditions logically.

Let's try this:

In [88]:
a = -3
b = 17

if (not a > 0) and b + a < 20:
    print('yay')


yay


## Functions
let us write our own *absolute value* function: $ f(x) = |x| $

In [32]:
# def defines a function of the following name
def absolute(x): # in parantheses are the arguments to the function
    print('Called absolute(', x, ')')
    if x < 0:
        return -x # return defines what the function 
    else:
        return x

In [92]:
a = absolute(-123)
print(a)

Called absolute( -123 )
123


Variables in functions have a **scope** limited to that of the function - but if they do not know a variable they look in the enclosing scope!

In [35]:
x = 12
absolute(5)

Called absolute( 5 )


5

In [41]:
def changeMyX():
    x = 999 # by assigning a value to x we 'bind' the variable name x to the value 999 within this function's scope.
    print(x)

In [93]:
changeMyX()

999


In [94]:
x # should be untouched as the function above did have its own x!

12

In [46]:
def printMyX():
    print(x) # there is no x inside this scope, looks in enclosing scope (=whole script)

In [96]:
x = 13
printMyX()

13


Functions can be nested

In [98]:
x = 12
def outerFunc():
    x = 17 # define variable in "outer"'s scope
    def innerFunc(): # define a function inside a function
        return x*2 # accesses outerFunc's x as this is the enclosing scope
    y = innerFunc()
    print(innerFunc())
    print(x)
    print(y)
    
outerFunc()
print(x) # global x should be untouched

17
34
12


In [ ]:
lhs = absolute(-12)
absolute(absolute(-12))






